import { beforeEach,afterEach,it,expect,vi } from 'vitest'
import { render,screen,fireEvent,cleanup,within,waitFor } from '@testing-library/react'
import { MemoryRouter } from 'react-router-dom'
import App from '../src/App'
import { welcomeVisit } from '../src/landing/WelcomeModal'
beforeEach(()=>{welcomeVisit.dismissed=true;window.scrollTo=vi.fn();Element.prototype.scrollIntoView=vi.fn();vi.stubGlobal('matchMedia',()=>({matches:false,addEventListener:vi.fn(),removeEventListener:vi.fn()}));HTMLDialogElement.prototype.showModal=function(){this.setAttribute('open','')};HTMLDialogElement.prototype.close=function(){this.removeAttribute('open')};localStorage.clear()})
afterEach(()=>{cleanup();vi.restoreAllMocks();vi.unstubAllGlobals()})
const mount=(path='/my')=>render(<MemoryRouter initialEntries={[path]}><App/></MemoryRouter>)
it('renders reference data and switches period sample totals',()=>{mount();expect(screen.getByRole('heading',{name:'Player123'})).toBeTruthy();expect(screen.getByText('−₱1,250.00')).toBeTruthy();fireEvent.change(screen.getByLabelText('Statistics period'),{target:{value:'Last month'}});expect(screen.getByText('₱850.00')).toBeTruthy();expect(screen.getByText('₱9,500.00')).toBeTruthy();expect(screen.getByRole('button',{name:'My',exact:true}).getAttribute('aria-current')).toBe('page')})
it('copies ID only after success and offers manual selection on failure',async()=>{const copy=vi.fn().mockResolvedValue(undefined);Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:copy}});mount();fireEvent.click(screen.getByRole('button',{name:'Copy account ID'}));await screen.findByText('ID copied.');expect(copy).toHaveBeenCalledWith('8891023');copy.mockRejectedValue(new Error('denied'));fireEvent.click(screen.getByRole('button',{name:'Copy account ID'}));expect(await screen.findByLabelText('Account ID to copy')).toBeTruthy();expect(screen.queryByText('ID copied.')).toBeNull()})
it('opens every account row with preview information and restores focus',()=>{mount();for(const name of ['Personal information','Account security','Verification','Preferences','Help center']){const b=screen.getByRole('button',{name,exact:true});b.focus();fireEvent.click(b);expect(screen.getByRole('dialog')).toBeTruthy();expect(document.body.style.overflow).toBe('hidden');fireEvent(screen.getByRole('dialog'),new Event('cancel',{cancelable:true}));expect(document.activeElement).toBe(b);expect(document.body.style.overflow).not.toBe('hidden')}})
it('supports record details',()=>{mount();fireEvent.click(screen.getByRole('button',{name:'View all',exact:true}));fireEvent.click(within(screen.getByRole('dialog')).getByRole('button',{name:'Fortune Ox'}));expect(screen.getByRole('dialog',{name:'Fortune Ox'}).textContent).toContain('₱1,000.00')})
it('confirms leaving preview without deleting favorites',()=>{localStorage.setItem('kun-king:favorites:v1','["98"]');mount();fireEvent.click(screen.getByRole('button',{name:'Log Out',exact:true}));fireEvent.click(screen.getByRole('button',{name:'Cancel'}));expect(screen.queryByRole('dialog')).toBeNull();fireEvent.click(screen.getByRole('button',{name:'Log Out',exact:true}));fireEvent.click(screen.getByRole('link',{name:'Leave Preview'}));expect(screen.getByRole('heading',{name:'Welcome back'})).toBeTruthy();expect(localStorage.getItem('kun-king:favorites:v1')).toBe('["98"]');expect(document.body.style.overflow).not.toBe('hidden')})
it('provides login register and favorites through profile',async()=>{mount();fireEvent.click(screen.getByRole('button',{name:'Edit profile'}));const d=within(screen.getByRole('dialog'));expect(d.getByRole('link',{name:'Log In'}).getAttribute('href')).toBe('/login');expect(d.getByRole('link',{name:'Register'})).toBeTruthy();fireEvent.click(d.getByRole('link',{name:'My Favorites'}));await waitFor(()=>expect(screen.getByRole('region',{name:'My Favorites',exact:true})).toBeTruthy())})

it.each(['/frontend','/promo','/my'])('uses public auth links in the shared header on %s',path=>{mount(path);const header=within(screen.getByRole('banner'));expect(header.queryByRole('link',{name:'Settings'})).toBeNull();expect(header.queryByRole('link',{name:'Notifications'})).toBeNull();expect(header.getByRole('link',{name:'Log In'}).getAttribute('href')).toBe('/login');expect(header.getByRole('link',{name:'Register'}).getAttribute('href')).toBe('/register')})
it.each([['Log In','Welcome back'],['Register','CreateAccount']])('navigates from My header via %s',(label,title)=>{mount();fireEvent.click(within(screen.getByRole('banner')).getByRole('link',{name:label}));expect(screen.getByRole('heading',{name:title,exact:true})).toBeTruthy()})

